<?php

/**
 * BaseTopGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $block_title
 * @property varchar $meta_critic_score
 * @property varchar $platform
 * @property int $cex_buy_price
 * @property int $cex_sell_price
 * @property int $cex_ex_price
 * @property enum $status
 * 
 * @method string  getTitle()             Returns the current record's "title" value
 * @method string  getBlockTitle()        Returns the current record's "block_title" value
 * @method varchar getMetaCriticScore()   Returns the current record's "meta_critic_score" value
 * @method varchar getPlatform()          Returns the current record's "platform" value
 * @method int     getCexBuyPrice()       Returns the current record's "cex_buy_price" value
 * @method int     getCexSellPrice()      Returns the current record's "cex_sell_price" value
 * @method int     getCexExPrice()        Returns the current record's "cex_ex_price" value
 * @method enum    getStatus()            Returns the current record's "status" value
 * @method TopGame setTitle()             Sets the current record's "title" value
 * @method TopGame setBlockTitle()        Sets the current record's "block_title" value
 * @method TopGame setMetaCriticScore()   Sets the current record's "meta_critic_score" value
 * @method TopGame setPlatform()          Sets the current record's "platform" value
 * @method TopGame setCexBuyPrice()       Sets the current record's "cex_buy_price" value
 * @method TopGame setCexSellPrice()      Sets the current record's "cex_sell_price" value
 * @method TopGame setCexExPrice()        Sets the current record's "cex_ex_price" value
 * @method TopGame setStatus()            Sets the current record's "status" value
 * 
 * @package    ebay-games
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTopGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('top_games');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('block_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('meta_critic_score', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('platform', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('cex_buy_price', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('cex_sell_price', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('cex_ex_price', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'live',
              1 => 'disabled',
             ),
             'default' => 'disabled',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             ));
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}