<?php

/**
 * BaseGameTitleFilter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filter
 * @property integer $num_spaces
 * 
 * @method string          getFilter()     Returns the current record's "filter" value
 * @method integer         getNumSpaces()  Returns the current record's "num_spaces" value
 * @method GameTitleFilter setFilter()     Sets the current record's "filter" value
 * @method GameTitleFilter setNumSpaces()  Sets the current record's "num_spaces" value
 * 
 * @package    ebay-games
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameTitleFilter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game_title_filters');
        $this->hasColumn('filter', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('num_spaces', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}