<?php

/**
 * EbayGameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EbayGameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EbayGameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EbayGame');
    }
}