<?php

/**
 * GameTitleFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameTitleFilterTable extends Doctrine_Table
{
  /**
    * Returns an instance of this class.
    *
    * @return object GameTitleFilterTable
    */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('GameTitleFilter');
  }

  /**
    * get all the filters order by the number of spaces
    * @return array list of filters 
    */
  public static function getGameTitleFilterBySpaces()
  {

    $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
    $query = "SELECT filter FROM game_title_filters ORDER BY num_spaces DESC";
    $stmt = $pdo->prepare($query);
    $stmt->execute();
    $results = $stmt->fetchAll(PDO::FETCH_COLUMN);  

    // return result
    return $results;
  }
}