<?php

/**
 * TopGameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TopGameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TopGameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TopGame');
    }
}