<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/19 17:09:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ebay_games',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
