<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/05/19 17:44:01
return array(

  // sfAdminThemejRollerPlugin_module_libs

  // sfAdminThemejRollerPlugin_lib
  'uihelper' => '/var/www/eBay-games-analysis/plugins/sfAdminThemejRollerPlugin/lib/helper/UIHelper.class.php',
  'jrollerdoctrinegenerator' => '/var/www/eBay-games-analysis/plugins/sfAdminThemejRollerPlugin/lib/jRollerDoctrineGenerator.class.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfformdoctrine' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinerecord' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinebasetask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinemigratetask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildfilterstask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinedqltask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildsqltask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinedataloadtask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildschematask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildmodeltask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildtask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinedatadumptask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinecreatemodeltables' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinegenerateadmintask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuildformstask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrineinsertsqltask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinedropdbtask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuilddbtask' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfwebdebugpaneldoctrine' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrineexception' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinedatabase' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionlistener' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfvalidatordoctrinechoice' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrinecolumn' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrinecli' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sftesterdoctrine' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'swift_doctrinespool' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineroute' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfwidgetformdoctrinechoice' => '/var/www/eBay-games-analysis/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basetopgameform' => '/var/www/eBay-games-analysis/lib/form/doctrine/base/BaseTopGameForm.class.php',
  'baseebaygameform' => '/var/www/eBay-games-analysis/lib/form/doctrine/base/BaseEbayGameForm.class.php',
  'topgameform' => '/var/www/eBay-games-analysis/lib/form/doctrine/TopGameForm.class.php',
  'baseformdoctrine' => '/var/www/eBay-games-analysis/lib/form/doctrine/BaseFormDoctrine.class.php',
  'ebaygameform' => '/var/www/eBay-games-analysis/lib/form/doctrine/EbayGameForm.class.php',
  'baseform' => '/var/www/eBay-games-analysis/lib/form/BaseForm.class.php',
  'basetopgameformfilter' => '/var/www/eBay-games-analysis/lib/filter/doctrine/base/BaseTopGameFormFilter.class.php',
  'baseebaygameformfilter' => '/var/www/eBay-games-analysis/lib/filter/doctrine/base/BaseEbayGameFormFilter.class.php',
  'topgameformfilter' => '/var/www/eBay-games-analysis/lib/filter/doctrine/TopGameFormFilter.class.php',
  'ebaygameformfilter' => '/var/www/eBay-games-analysis/lib/filter/doctrine/EbayGameFormFilter.class.php',
  'baseformfilterdoctrine' => '/var/www/eBay-games-analysis/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'parsemetacriticgamestask' => '/var/www/eBay-games-analysis/lib/task/parseMetaCriticGamesTask.class.php',
  'parsegamesfromebaytask' => '/var/www/eBay-games-analysis/lib/task/parseGamesFromeBayTask.class.php',

  // project_model
  'basetopgame' => '/var/www/eBay-games-analysis/lib/model/doctrine/base/BaseTopGame.class.php',
  'baseebaygame' => '/var/www/eBay-games-analysis/lib/model/doctrine/base/BaseEbayGame.class.php',
  'ebaygametable' => '/var/www/eBay-games-analysis/lib/model/doctrine/EbayGameTable.class.php',
  'topgametable' => '/var/www/eBay-games-analysis/lib/model/doctrine/TopGameTable.class.php',
  'topgame' => '/var/www/eBay-games-analysis/lib/model/doctrine/TopGame.class.php',
  'ebaygame' => '/var/www/eBay-games-analysis/lib/model/doctrine/EbayGame.class.php',

  // application
  'myuser' => '/var/www/eBay-games-analysis/apps/frontend/lib/myUser.class.php',

  // modules
);
