<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/19 14:04:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ebay_games',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
