GameTitleFilter:
  tableName: game_title_filters
  columns:
    filter: string(255)
    num_spaces: integer

TopGame:
  tableName: top_games
  actAs: [Sluggable, Timestampable]
  columns:
    title: string(255)
    block_title: string(255)
    meta_critic_score: varchar(20)
    platform: varchar(20)
    cex_buy_price: int(11)
    cex_sell_price: int(11)
    cex_ex_price: int(11)
    status:
      type: enum
      values: [live, disabled]
      default: disabled
    
EbayGame:
  tableName: ebay_games
  actAs: [Sluggable, Timestampable]
  columns:
    guid: { type: string(255), unique: true }      
    title: string(255)
    clean_title: string(255)
    block_title: string
    link: string(255)
    description: text
    current_price: int(11)
    end_time: int(11)
    bid_count: int(11)
    postage_packing_fee: int(11)
    profile_name: varchar(255)
    profile_url: varchar(255)
    feedback_score: int(11)
    title_processed: tinyint(1)
    platform: varchar(20)
    status:
      type: enum
      values: [live, ended]
      default: live